project:
  type: website

website:
  title: "Decoding Chaos"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    logo: "images/logo.png"
    title: false
    search: true
    
    right:
      - text: "Overview"
        href: "Poster/Poster.html"
        
      - text: "Shiny App"
        menu:
        - text: "Shiny App"
          href: "https://group5vaa.shinyapps.io/Decoding-Chaos/"
        - text: "User Guide"
          href: "RShiny/UserGuide.pdf"

      - text: "Prototype"
        menu: 
        - text: "Aspatial Analysis"
          href: "Prototype/Aspatial Analysis/AspatialAnalysis.html"
        - text: "Geospatial Analysis - 1"
          href: "Prototype/Geospatial Analysis/GeospatialAnalysis1.html"
        - text: "Geospatial Analysis - 2"
          href: "Prototype/Geospatial Analysis/GeospatialAnalysis2.html"
        - text: "Confirmatory Analysis"
          href: "Prototype/Confirmatory Analysis/ConfirmatoryAnalysis.html"
        - text: "Storyboard"
          href: "Prototype/Storyboard/Storyboard.html"
      
      - text: "Team"
        menu:
        - text: "Project Proposal"
          href: "Team/ProjectProposal/ProjectProposal(list).html"
        - text: "Meeting Records"
          href: "Team/MeetingMinutes/ProjectMeeting.html"
        - text: "Acknowledgement"
          href: "Team/Team.html"
    
  page-footer:
    right: 
      - text: "©2024!"

format:
  html:
    theme:
      - flatly
      - theme.scss
    mermaid: 
      theme: neutral
    css: styles.css
    grid:
      sidebar-width: 100px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 2.0rem
editor: visual